services:
  postgres:
    image: postgres
    container_name: nestjs-blog-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs-blog
    volumes:
      - data_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: nestjs-blog-redis
    ports:
      - '63798:6379'
    volumes:
      - data_redis:/data

volumes:
  data_postgres:
  data_redis:
